const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['src/app.js']
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8081",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [

    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        asignarTarea: {
            "fechaInicio": "2021/09/20",
            "fechaFin": "2021/10/5",
            "observacion": "obs_5",
            "idOti": "616f2980c5e1d1846975c8cd",
            "idOperario": "613e6361b2153ee73d786bc9",
            "tareas": [{
                "descripcion": "hola hola 3",
                "nombre": "tarea nueva2",
                "fechaInicio": "2009-11-11T03:00:00.000Z",
                "fechaFin": "2009-11-15T03:00:00.000Z",
                "tipoDeTarea": {
                    "nombre": "tarea5",
                    "descripcion": "descripcion_5",
                    "_id": "616f2981c5e1d1846975c8f6"
                },
                "sector": {
                    "nombre": "deposito",
                    "operario": [],
                    "_id": "616f2981c5e1d1846975c8f7"
                },
                "idOperario": "613e626ab2153ee73d77fb1d",
                "estado": [
                    {
                        "fechaInicio": "2009-11-11T03:00:00.000Z",
                        "fechaFin": "2009-11-15T03:00:00.000Z",
                        "observacion": "creado correctamente",
                        "tipoEstado": {
                            "nombre": "iniciada",
                            "descripcion": "se inicializo correctamente",
                            "_id": "616f2981c5e1d1846975c8f9"
                        },
                        "_id": "616f2981c5e1d1846975c8f8"

                    }
                ],
                "_id": "616f2981c5e1d1846975c8f5"


            }]
        },
        tarea: {
            "_id": "617414850300be212f4f1b6c",
            "descripcion": "hola hola 2",
            "nombre": "tarea nueva2",
            "fechaInicio": "2009-11-11T03:00:00.000Z",
            "fechaFin": "2009-11-15T03:00:00.000Z",
            "tipoDeTarea": {
                "nombre": "tarea5",
                "descripcion": "descripcion_5",
                "_id": "617414850300be212f4f1b6d"
            },
            "sector": {
                "nombre": "corte",
                "operario": [],
                "_id": "617414850300be212f4f1b6e"
            },
            "idOperario": "613bc8c397d979667ca2a137",
            "estado": [
                {
                    "fechaInicio": "2009-11-11T03:00:00.000Z",
                    "fechaFin": "2009-11-15T03:00:00.000Z",
                    "observacion": "creado correctamente",
                    "tipoEstado": {
                        "nombre": "iniciada",
                        "descripcion": "se inicializo correctamente",
                        "_id": "617414850300be212f4f1b70"
                    },
                    "_id": "617414850300be212f4f1b6f"

                },
                {
                    "fechaInicio": "2021-11-22T03:00:00.000Z",
                    "fechaFin": '',
                    "observacion": "caso de test",
                    "tipoEstado": {
                        "nombre": "en progreso",
                        "descripcion": "en progreso...",
                        "_id": "613bcf1597d979667ca2a15f"
                    },
                    "_id": "619c0f1ec5109632f26ef43a"

                }
            ],

        },
        sector: {
            "operario": [],
            "_id": "613bc737b2153ee73d448bf1",
            "nombre": "corte",
            "activo": true,
            "operarios": [
                {
                    "_id": "613e631eb2153ee73d784e23",
                    "numeroEmpleado": 3,
                    "DNI": "89-620-4885",
                    "nombre": "Fidelio",
                    "apellido": "Tedorenko",
                    "telefono": "332-243-1445",
                    "nombreUsuario": "ftedorenko2",
                    "contraseña": "eErDOWk7jQj0",
                    "email": "ftedorenko2@ucoz.ru",
                    "sector": {
                        "nombre": "corte"
                    }
                },
                {
                    "_id": "613e626ab2153ee73d77fb1d",
                    "numeroEmpleado": 1,
                    "DNI": "75-185-5002",
                    "nombre": "Therine",
                    "apellido": "Schwandermann",
                    "telefono": "425-399-3968",
                    "nombreUsuario": "tschwandermann0",
                    "contraseña": "jMG4WqP17XBK",
                    "email": "tschwandermann0@seesaa.net",
                    "sector": {
                        "nombre": "corte"
                    }
                }
            ]
        },
        arraySector: {
            "_id": "613bc737b2153ee73d448bf1",
            "nombre": "corte",
            "activo": true,
            "operarios": [
                {
                    "_id": "613e631eb2153ee73d784e23",
                    "numeroEmpleado": 3,
                    "DNI": "89-620-4885",
                    "nombre": "Fidelio",
                    "apellido": "Tedorenko",
                    "telefono": "332-243-1445",
                    "nombreUsuario": "ftedorenko2",
                    "contraseña": "eErDOWk7jQj0",
                    "email": "ftedorenko2@ucoz.ru",
                    "sector": {
                        "nombre": "corte"
                    }
                }
            ]
        },
        rosca: {
            "_id": "61a161477146661f9d634386",
            "descripcionTecnica": "con corte especial en los ultimos 3/4 , para perforaciones horizontales y verticales",
            "medida": "asd",
            "tipoDeRosca": {
                "descripcion": "",
                "nombre": "TDL",
                "categoria": {
                    "nombre": "premium",
                    "descripcion": "exportacion marina y utilizacion para caños de gas",
                    "_id": "61a1611f7146661f9d634384"
                },
                "_id": "613e604acb4275f300506790"
            },

        },
        arrayTipoDeRosca: [{
            "_id": "613e604acb4275f300506790",
            "descripcion": "descripcion_5",
            "nombre": "TDL",
            "categoria": {
                "_id": "61a391f17d3c127a35ddfa41",
                "nombre": "premium",
                "descripcion": "exportacion marina y utilizacion para caños de gas"
            }
        }],
        arrayRoscas: [{
            "_id": "61a161477146661f9d634386",
            "descripcionTecnica": "con corte especial en los ultimos 3/4 , para perforaciones horizontales y verticales",
            "medida": "asd",
            "tipoDeRosca": {
                "descripcion": "",
                "nombre": "TDL",
                "categoria": {
                    "nombre": "premium",
                    "descripcion": "exportacion marina y utilizacion para caños de gas",
                    "_id": "61a1611f7146661f9d634384"
                },
                "_id": "613e604acb4275f300506790"
            },
        }],
        oti: {
            "_id": "613e5777b2153ee73d73142f",
            "fechaFin": '',
            "rosca": {
                "descripcionTecnica": "es una rosca dificil de hacer",
                "medida": "20x50x10",
                "tipoDeRosca": {
                    "descripcion": "la mejor rosca",
                    "categoria": {
                        "nombre": "premium",
                        "descripcion": "exportacion marina y utilizacion para caños de gas",
                        "_id": "615e53c8db8fc5cc55e1fb3d"
                    },
                    "_id": "615e53c8db8fc5cc55e1fb3c"
                },
                "_id": "615e53c8db8fc5cc55e1fb3b"
            },
            "sector": [
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf810",
                    "nombre": "torneria"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf811",
                    "nombre": "corte"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf812",
                    "nombre": "calidad"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf813",
                    "nombre": "deposito"
                }
            ],
            "tareas": [
                {
                    "descripcion": "descripcion_1",
                    "nombre": "tarea_1",
                    "fechaInicio": "2020-04-01T03:00:00.000Z",
                    "fechaFin": "2020-04-03T03:00:00.000Z",
                    "numeroDeOrden": 1,
                    "tipoDeTarea": {
                        "nombre": "tarea1",
                        "descripcion": "descripcion_1",
                        "_id": "615e53c8db8fc5cc55e1fb3f"
                    },
                    "sector": {
                        "operario": [],
                        "nombre": "corte",
                        "_id": "615e53c8db8fc5cc55e1fb40"
                    },
                    "estado": [],
                    "_id": "615e53c8db8fc5cc55e1fb3e"
                },
                {
                    "descripcion": "descripcion_2",
                    "nombre": "tarea_2",
                    "fechaInicio": "2020-03-02T03:00:00.000Z",
                    "fechaFin": "2020-01-04T03:00:00.000Z",
                    "numeroDeOrden": 2,
                    "tipoDeTarea": {
                        "nombre": "tarea3",
                        "descripcion": "descripcion_3",
                        "_id": "615e53c8db8fc5cc55e1fb42"
                    },
                    "sector": {
                        "operario": [],
                        "nombre": "deposito",
                        "_id": "615e53c8db8fc5cc55e1fb43"
                    },
                    "estado": [],
                    "_id": "615e53c8db8fc5cc55e1fb41"
                }
            ],
            "estados": [
                {
                    "fechaInicio": "2021-09-20T03:00:00.000Z",
                    "fechaFin": "2021-10-05T03:00:00.000Z",
                    "observacion": "obs_5",
                    "tipoEstado": {
                        "nombre": "EN PROGRESO",
                        "descripcion": "",
                        "_id": "615e53c8db8fc5cc55e1fb47"
                    },
                    "_id": "615e53c8db8fc5cc55e1fb46"

                },
                {
                    "fechaInicio": "2021-09-20T03:00:00.000Z",
                    "fechaFin": "2021-10-05T03:00:00.000Z",
                    "observacion": "obs_5",
                    "tipoEstado": {
                        "nombre": "Iniciada",
                        "descripcion": "",
                        "_id": "615e5b1e2968697488389e79"
                    },
                    "_id": "615e5b1e2968697488389e78"

                }
            ]
        },
        arrayOti: [{
            "_id": "613e5777b2153ee73d73142f",
            "fechaFin": '',
            "rosca": {
                "descripcionTecnica": "es una rosca dificil de hacer",
                "medida": "20x50x10",
                "tipoDeRosca": {
                    "descripcion": "la mejor rosca",
                    "categoria": {
                        "nombre": "premium",
                        "descripcion": "exportacion marina y utilizacion para caños de gas",
                        "_id": "615e53c8db8fc5cc55e1fb3d"
                    },
                    "_id": "615e53c8db8fc5cc55e1fb3c"
                },
                "_id": "615e53c8db8fc5cc55e1fb3b"
            },
            "sector": [
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf810",
                    "nombre": "torneria"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf811",
                    "nombre": "corte"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf812",
                    "nombre": "calidad"
                },
                {
                    "operario": [],
                    "_id": "61a382527d3c127a35ddf813",
                    "nombre": "deposito"
                }
            ],
            "tareas": [
                {
                    "descripcion": "descripcion_1",
                    "nombre": "tarea_1",
                    "fechaInicio": "2020-04-01T03:00:00.000Z",
                    "fechaFin": "2020-04-03T03:00:00.000Z",
                    "numeroDeOrden": 1,
                    "tipoDeTarea": {
                        "nombre": "tarea1",
                        "descripcion": "descripcion_1",
                        "_id": "615e53c8db8fc5cc55e1fb3f"
                    },
                    "sector": {
                        "operario": [],
                        "nombre": "corte",
                        "_id": "615e53c8db8fc5cc55e1fb40"
                    },
                    "estado": [],
                    "_id": "615e53c8db8fc5cc55e1fb3e"
                },
                {
                    "descripcion": "descripcion_2",
                    "nombre": "tarea_2",
                    "fechaInicio": "2020-03-02T03:00:00.000Z",
                    "fechaFin": "2020-01-04T03:00:00.000Z",
                    "numeroDeOrden": 2,
                    "tipoDeTarea": {
                        "nombre": "tarea3",
                        "descripcion": "descripcion_3",
                        "_id": "615e53c8db8fc5cc55e1fb42"
                    },
                    "sector": {
                        "operario": [],
                        "nombre": "deposito",
                        "_id": "615e53c8db8fc5cc55e1fb43"
                    },
                    "estado": [],
                    "_id": "615e53c8db8fc5cc55e1fb41"
                }
            ],
            "estados": [
                {
                    "fechaInicio": "2021-09-20T03:00:00.000Z",
                    "fechaFin": "2021-10-05T03:00:00.000Z",
                    "observacion": "obs_5",
                    "tipoEstado": {
                        "nombre": "EN PROGRESO",
                        "descripcion": "",
                        "_id": "615e53c8db8fc5cc55e1fb47"
                    },
                    "_id": "615e53c8db8fc5cc55e1fb46",
                    "__v": 0
                },
                {
                    "fechaInicio": "2021-09-20T03:00:00.000Z",
                    "fechaFin": "2021-10-05T03:00:00.000Z",
                    "observacion": "obs_5",
                    "tipoEstado": {
                        "nombre": "Iniciada",
                        "descripcion": "",
                        "_id": "615e5b1e2968697488389e79"
                    },
                    "_id": "615e5b1e2968697488389e78"

                }
            ]
        }],
        Ordenes: [{
            "_id": "619c3f28a5e105f51b94f683",
            "detalle": "detalle",
            "fecha": "2021-11-22",
            "supervisor": {
                "numeroEmpleado": "5",
                "DNI": "205967118",
                "nombre": "Suzanne",
                "apellido": "Kleynermans",
                "telefono": "253-396-2243",
                "nombreUsuario": "skleynermans4",
                "contraseña": "LACiCk",
                "email": "skleynermans4@acquirethisname.com",
                "_id": "613bc8c397d979667ca2a13a"
            },
            "oti": [],
            "rosca": [
                {
                    "descripcionTecnica": "descripcion",
                    "medida": "30x30x30",
                    "tipoDeRosca": {
                        "descripcion": "descripcion_5",
                        "nombre": "TDL",
                        "categoria": {
                            "nombre": "premium",
                            "descripcion": "exportacion marina y utilizacion para caños de gas",
                            "_id": "619c3f28a5e105f51b94f67e"
                        },
                        "_id": "613e604acb4275f300506790"
                    },
                    "_id": "619c3f28a5e105f51b94f67f"
                }
            ],
        }],
        orden: {
            "_id": "619c3f28a5e105f51b94f683",
            "detalle": "detalle",
            "fecha": "2021-11-22",
            "supervisor": {
                "numeroEmpleado": "5",
                "DNI": "205967118",
                "nombre": "Suzanne",
                "apellido": "Kleynermans",
                "telefono": "253-396-2243",
                "nombreUsuario": "skleynermans4",
                "contraseña": "LACiCk",
                "email": "skleynermans4@acquirethisname.com",
                "_id": "613bc8c397d979667ca2a13a"
            },
            "oti": [],
            "rosca": [
                {
                    "descripcionTecnica": "descripcion",
                    "medida": "30x30x30",
                    "tipoDeRosca": {
                        "descripcion": "descripcion_5",
                        "nombre": "TDL",
                        "categoria": {
                            "nombre": "premium",
                            "descripcion": "exportacion marina y utilizacion para caños de gas",
                            "_id": "619c3f28a5e105f51b94f67e"
                        },
                        "_id": "613e604acb4275f300506790"
                    },
                    "_id": "619c3f28a5e105f51b94f67f",

                }
            ],

        },
        cliente: {
            "_id": "613e54dacb4275f300506776",
            "DNI": "30698993.0",
            "CUIT": "20306989934.0",
            "nombre": "Melamie",
            "apellido": "Bamblett",
            "telefono": "724 673 2004",
            "correo": "mbamblett3@wordpress.com",
            "nombreEmpresa": "Vimbo",
            "ordenProduccion": [
                {
                    "idOrdenProduccion": "613bc8c397d979667ddda137",
                    "fecha": "07/05/2021",
                    "detalle": "400 roscas para plataforma marina",
                    "estado": "finaliza"
                }
            ]
        },
        clientes: [
            {
                "_id": "613e54dacb4275f300506776",
                "DNI": "30698993.0",
                "CUIT": "20306989934.0",
                "nombre": "Melamie",
                "apellido": "Bamblett",
                "telefono": "724 673 2004",
                "correo": "mbamblett3@wordpress.com",
                "nombreEmpresa": "Vimbo",
                "ordenProduccion": [
                    {
                        "idOrdenProduccion": "613bc8c397d979667ddda137",
                        "fecha": "07/05/2021",
                        "detalle": "400 roscas para plataforma marina",
                        "estado": "finaliza"
                    }
                ]
            }],

        empleado: {
            "_id": "613bc8c397d979667ca2a137",
            "numeroEmpleado": "2",
            "DNI": "66316022",
            "nombre": "walter",
            "apellido": "garrido",
            "telefono": "850-421-9067",
            "nombreUsuario": "operario1234",
            "contraseña": "12345",
            "email": "walter.garrido@est.fi.uncoma.edu.ar",
            "funcion": "operario"
        },
        operarios: [{
            "_id": "613bc8c397d979667ca2a137",
            "numeroEmpleado": "2",
            "DNI": "66316022",
            "nombre": "walter",
            "apellido": "garrido",
            "telefono": "850-421-9067",
            "nombreUsuario": "operario1234",
            "contraseña": "12345",
            "email": "walter.garrido@est.fi.uncoma.edu.ar",
        }],
        operario: {
            "_id": "613bc8c397d979667ca2a137",
            "numeroEmpleado": "2",
            "DNI": "66316022",
            "nombre": "walter",
            "apellido": "garrido",
            "telefono": "850-421-9067",
            "nombreUsuario": "operario1234",
            "contraseña": "12345",
            "email": "walter.garrido@gmail.com.ar",
        },
        supervisor: {
            "_id": "613bc8ccc7d979667ca2a137",
            "numeroEmpleado": "2",
            "DNI": "66316022",
            "nombre": "martin",
            "apellido": "garcia",
            "telefono": "850-421-9067",
            "nombreUsuario": "supervisor1234",
            "contraseña": "12345",
            "email": "martingarcia@gmail.com",
        },
        arraySupervisores: [{
            "_id": "613bc8ccc7d979667ca2a137",
            "numeroEmpleado": "2",
            "DNI": "66316022",
            "nombre": "martin",
            "apellido": "garcia",
            "telefono": "850-421-9067",
            "nombreUsuario": "supervisor1234",
            "contraseña": "12345",
            "email": "martingarcia@gmail.com",
        }],
        estados: [
            {
                "_id": "613bcf1597d979667ca2a160",
                "nombre": "detenida",
                "descripcion": "ah ocurrido un problema"
            },
            {
                "_id": "613bcf1597d979667ca2a15f",
                "nombre": "en progreso",
                "descripcion": "en progreso..."
            },
            {
                "_id": "613bcf1597d979667ca2a15e",
                "nombre": "iniciada",
                "descripcion": "aun no ha comenzado"
            },
            {
                "_id": "613bcf1597d979667ca2a161",
                "nombre": "abortada",
                "descripcion": "no pudo solucionarse"
            },
            {
                "_id": "613bcf1597d979667ca2a162",
                "nombre": "finalizada",
                "descripcion": "ha finalizado con exito"
            }
        ],
        tareas: {
            tareasOperario: [{
                descripcion: 'asignar a operario con experiencia',
                nombre: 'cortar pieza',
                fechaInicio: 'YYYY/MM/DD',
                fechaFin: 'YYYY/MM/DD',
                numeroDeOrden: '4589',
                tipoDeTarea: 'tareas de corte',
                sector: {
                    nombre: 'corte',
                    activo: 'true',
                    operario: ['5ea7029320e515102e44c71d', '5ea7029320e515102ed5c22d', '5ea7029320e515222102ed5c71d', '5ea7029320e515123pc71d'],
                },
                idOperario: '5ea7029320e515102e44c71d',
                estado: [{
                    fechaInicio: 'YYYY/MM/DD',
                    fechaFin: 'YYYY/MM/DD',
                    observacion: 'se crea la tarea',
                    tipoEstado: {
                        nombre: "iniciada",
                        descripcion: "se encuentra lista para ponerse en produccion",
                    }
                },
                {
                    fechaInicio: 'YYYY/MM/DD',
                    fechaFin: 'YYYY/MM/DD',
                    observacion: 'si inicia con todos las herramientas calibradas',
                    tipoEstado: {
                        nombre: "en progreso",
                        descripcion: "en proceso de produccion",
                    }
                }]
            }],
            idOti: '616f2980c5e1d1846975c8cd',
        },
        cambioEstado: {
            idOti: "616f2980c5e1d1846975c8cd",
            idTarea: "616f2981c5e1d1846975c8f5",
            nombreSector: "corte",
            observacion: "se inicia proceso de produccion de tarea",
            tipoEstado: {
                nombre: "en progreso",
                descripcion: "en proceso de produccion"
            }
        }

    }
}
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})
